import type { Theme } from './index'

export const flatDesign: Theme = {
  name: 'flat-design',
  label: '扁平设计',
  labelEn: 'Flat Design',
  fonts: {
    sans: '"Open Sans", -apple-system, BlinkMacSystemFont, sans-serif',
    serif: '"Open Sans", Georgia, serif',
    mono: '"JetBrains Mono", "SF Mono", "Fira Code", monospace',
  },
  colors: {
    bgPage: '#ffffff',
    bgSurface: '#ffffff',
    bgMuted: '#f3f4f6',
    bgHeader: '#f3f4f6',
    border: '#e5e7eb',
    borderLight: '#f3f4f6',
    textPrimary: '#1f2937',
    textSecondary: '#6b7280',
    textTertiary: '#9ca3af',
    textHeader: '#6b7280',
    accent: '#3498db',
    accentLight: '#dbeafe',
    accentText: '#1d4ed8',
    statusOk: '#27ae60',
    statusWarn: '#f39c12',
    statusError: '#e74c3c',
    statusMuted: '#9ca3af',
    badgeOkBg: '#d1fae5',
    badgeWarnBg: '#fef3c7',
    badgeErrorBg: '#fee2e2',
    badgeAccentBg: '#dbeafe',
    badgeMutedBg: '#f3f4f6',
    badgeOkText: '#166534',
    badgeWarnText: '#92400e',
    badgeErrorText: '#991b1b',
    badgeAccentText: '#1d4ed8',
    badgeComicBg: '#dbeafe',
    badgeComicText: '#1d4ed8',
    badgeNovelBg: '#ede9fe',
    badgeNovelText: '#6d28d9',
    badgeDiscussionBg: '#fff7ed',
    badgeDiscussionText: '#c2410c',
    badgeMixedBg: '#fce7f3',
    badgeMixedText: '#be185d',
  },
  radius: { sm: '2px', md: '4px', lg: '6px', full: '9999px' },
  shadow: { card: 'none', elevated: 'none' },
}
