import type { Theme } from './index'

export const neubrutalism: Theme = {
  name: 'neubrutalism',
  label: '新粗野主义',
  labelEn: 'Neubrutalism',
  fonts: {
    sans: '"Space Grotesk", -apple-system, BlinkMacSystemFont, sans-serif',
    serif: '"Space Grotesk", Georgia, serif',
    mono: '"Space Grotesk", "JetBrains Mono", monospace',
  },
  colors: {
    bgPage: '#FFF8E7',
    bgSurface: '#ffffff',
    bgMuted: '#fff0d0',
    bgHeader: '#FFE66D',
    border: '#000000',
    borderLight: '#000000',
    textPrimary: '#000000',
    textSecondary: '#1a1a1a',
    textTertiary: '#4a4a4a',
    textHeader: '#000000',
    accent: '#FF6B6B',
    accentLight: '#ffe0e0',
    accentText: '#000000',
    statusOk: '#4ECDC4',
    statusWarn: '#FFE66D',
    statusError: '#FF6B6B',
    statusMuted: '#4a4a4a',
    badgeOkBg: '#4ECDC4',
    badgeWarnBg: '#FFE66D',
    badgeErrorBg: '#FF6B6B',
    badgeAccentBg: '#FF6B6B',
    badgeMutedBg: '#fff0d0',
    badgeOkText: '#000000',
    badgeWarnText: '#000000',
    badgeErrorText: '#000000',
    badgeAccentText: '#000000',
    badgeMutedText: '#4a4a4a',
    badgeComicBg: '#A8E6CF',
    badgeComicText: '#000000',
    badgeNovelBg: '#C4A1FF',
    badgeNovelText: '#000000',
    badgeDiscussionBg: '#FFE66D',
    badgeDiscussionText: '#000000',
    badgeMixedBg: '#FFB6B9',
    badgeMixedText: '#000000',
  },
  radius: { sm: '0px', md: '0px', lg: '0px', full: '0px' },
  shadow: {
    card: '4px 4px 0 0 #000000',
    elevated: '8px 8px 0 0 #000000',
  },
  effects: {
    borderWidth: '4px',
  },
}
