import type { Theme } from './index'

export const neumorphism: Theme = {
  name: 'neumorphism',
  label: '新拟态',
  labelEn: 'Neumorphism',
  fonts: {
    sans: '"Inter", -apple-system, BlinkMacSystemFont, sans-serif',
    serif: '"Inter", Georgia, serif',
    mono: '"JetBrains Mono", "SF Mono", "Fira Code", monospace',
  },
  colors: {
    bgPage: '#e8e8e8',
    bgSurface: '#e8e8e8',
    bgMuted: '#dedede',
    bgHeader: '#e0e0e0',
    border: '#d4d4d4',
    borderLight: '#dfdfdf',
    textPrimary: '#2d2d2d',
    textSecondary: '#5c5c5c',
    textTertiary: '#8a8a8a',
    textHeader: '#5c5c5c',
    accent: '#5b7fff',
    accentLight: '#dce3ff',
    accentText: '#3d5bd9',
    statusOk: '#4caf50',
    statusWarn: '#ff9800',
    statusError: '#f44336',
    statusMuted: '#8a8a8a',
    badgeOkBg: '#e8f5e9',
    badgeWarnBg: '#fff3e0',
    badgeErrorBg: '#ffebee',
    badgeAccentBg: '#e8ecff',
    badgeMutedBg: '#e0e0e0',
    badgeOkText: '#2e7d32',
    badgeWarnText: '#e65100',
    badgeErrorText: '#c62828',
    badgeAccentText: '#3d5bd9',
    badgeComicBg: '#e8ecff',
    badgeComicText: '#3d5bd9',
    badgeNovelBg: '#f3e8ff',
    badgeNovelText: '#6b3fbf',
    badgeDiscussionBg: '#fff3e0',
    badgeDiscussionText: '#e65100',
    badgeMixedBg: '#fce8f0',
    badgeMixedText: '#b83a78',
  },
  radius: { sm: '10px', md: '14px', lg: '20px', full: '9999px' },
  shadow: {
    card: '6px 6px 14px #d1d1d1, -6px -6px 14px #ffffff',
    elevated: '8px 8px 18px #cfcfcf, -8px -8px 18px #ffffff',
  },
}
