import type { Theme } from './index'

export const pixelArt: Theme = {
  name: 'pixel-art',
  label: '像素艺术',
  labelEn: 'Pixel Art',
  fonts: {
    sans: '"Press Start 2P", "Courier New", monospace',
    serif: '"Press Start 2P", "Courier New", monospace',
    mono: '"Press Start 2P", "Courier New", monospace',
  },
  colors: {
    bgPage: '#0f380f',
    bgSurface: '#1a4a1a',
    bgMuted: '#225522',
    bgHeader: '#184018',
    border: '#0f380f',
    borderLight: '#1a4a1a',
    textPrimary: '#9bbc0f',
    textSecondary: '#8bac0f',
    textTertiary: '#688820',
    textHeader: '#8bac0f',
    accent: '#9bbc0f',
    accentLight: '#1a4a1a',
    accentText: '#b0d010',
    statusOk: '#9bbc0f',
    statusWarn: '#d0b020',
    statusError: '#d04040',
    statusMuted: '#688820',
    badgeOkBg: '#1a3a10',
    badgeWarnBg: '#2a2a10',
    badgeErrorBg: '#2a1010',
    badgeAccentBg: '#1a3a10',
    badgeMutedBg: '#1a2a1a',
    badgeOkText: '#9bbc0f',
    badgeWarnText: '#d0b020',
    badgeErrorText: '#d04040',
    badgeAccentText: '#9bbc0f',
    badgeComicBg: '#1a3a10',
    badgeComicText: '#9bbc0f',
    badgeNovelBg: '#1a2a2a',
    badgeNovelText: '#80b0b0',
    badgeDiscussionBg: '#2a2a10',
    badgeDiscussionText: '#d0b020',
    badgeMixedBg: '#2a1a2a',
    badgeMixedText: '#c080c0',
  },
  radius: { sm: '0px', md: '0px', lg: '0px', full: '0px' },
  shadow: { card: 'none', elevated: 'none' },
  effects: {
    borderWidth: '3px',
  },
}
