import { useCallback, useEffect, useRef, useState } from 'react'
import { api } from '../api/client'
import type { ChatContext, ChatMessage, ChatSession } from '../types/chat'
const SELECTED = 'yamibo.chat.selected-session.v3'
const DRAFTS = 'yamibo.chat.drafts.v3'
function read<T>(key:string, fallback:T):T { try { const value=localStorage.getItem(key); return value ? JSON.parse(value) as T : fallback } catch { return fallback } }
function write(key:string, value:unknown) { try { localStorage.setItem(key, JSON.stringify(value)) } catch { /* storage is optional */ } }
export function useChatSessions() {
  const [context,setContext]=useState<ChatContext|null>(null); const [sessions,setSessions]=useState<ChatSession[]>([]); const [selected,setSelectedState]=useState<string>(()=>{try{return localStorage.getItem(SELECTED)||''}catch{return ''}}); const selectedRef=useRef(selected)
  const [messages,setMessages]=useState<ChatMessage[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [operationError,setOperationError]=useState<string|null>(null); const [operation,setOperation]=useState<string|null>(null); const [hasMore,setHasMore]=useState(false); const [drafts,setDrafts]=useState<Record<string,string>>(()=>read(DRAFTS,{})); const [offset,setOffset]=useState(0); const loadingMore=useRef(false); const messageRequest=useRef(0); const messagesAbort=useRef<AbortController|null>(null); const sessionsRef=useRef<ChatSession[]>([])
  useEffect(()=>{sessionsRef.current=sessions},[sessions]); useEffect(()=>{selectedRef.current=selected},[selected])
  const currentDraft=selected ? drafts[selected] || '' : ''
  const setDraft=useCallback((value:string)=>{if(!selectedRef.current)return;setDrafts(prev=>{const next={...prev,[selectedRef.current]:value};write(DRAFTS,next);return next})},[])
  const refreshMessages=useCallback(async(id?:string)=>{const target=id||selectedRef.current;if(!target)return;const token=++messageRequest.current;messagesAbort.current?.abort();const controller=new AbortController();messagesAbort.current=controller;try{const rows=await api.chatMessages(target,controller.signal);if(token===messageRequest.current&&target===selectedRef.current)setMessages(rows)}catch(e){if((e as Error).name!=='AbortError'&&token===messageRequest.current&&target===selectedRef.current)setError((e as Error).message)}},[])
  const select=useCallback(async(id:string)=>{selectedRef.current=id;setSelectedState(id);write(SELECTED,id);setMessages([]);void refreshMessages(id)},[refreshMessages])
  const load=useCallback(async(reset=true)=>{if(!reset&&loadingMore.current)return;loadingMore.current=!reset;setLoading(reset);try{const [ctx,page]=await Promise.all([reset?api.chatContext():Promise.resolve(context),api.chatSessions({limit:50,offset:reset?0:offset})]);const rows=page.sessions||page.items||[];setContext(ctx);setSessions(prev=>{const merged=reset?rows:[...prev,...rows.filter(row=>!prev.some(old=>old.id===row.id))];return merged});const nextOffset=(reset?0:offset)+rows.length;setOffset(nextOffset);setHasMore(page.has_more??rows.length===50);const chosen=selectedRef.current&&rows.some(row=>row.id===selectedRef.current)?selectedRef.current:reset?rows[0]?.id||'':selectedRef.current;if(reset&&chosen&&chosen!==selectedRef.current)await select(chosen);else if(reset&&chosen)await refreshMessages(chosen)}catch(e){setError((e as Error).message)}finally{setLoading(false);loadingMore.current=false}},[context,offset,refreshMessages,select])
  useEffect(()=>{void load();return()=>{messagesAbort.current?.abort()}},[]) // initial authority load
  const operationCall=useCallback(async<T>(name:string,fn:()=>Promise<T>)=>{setOperation(name);setOperationError(null);try{return await fn()}catch(e){setOperationError((e as Error).message);throw e}finally{setOperation(null)}},[])
  const create=useCallback(async(title?:string)=>operationCall('create',async()=>{const row=await api.createChatSession(title);setSessions(prev=>[row,...prev]);await select(row.id);return row}),[operationCall,select])
  const rename=useCallback(async(id:string,title:string)=>operationCall('rename',async()=>{const row=await api.renameChatSession(id,title);setSessions(prev=>prev.map(item=>item.id===id?{...item,...row}:item))}),[operationCall])
  const remove=useCallback(async(id:string)=>operationCall('delete',async()=>{await api.deleteChatSession(id);const current=sessionsRef.current.filter(item=>item.id!==id);setSessions(current);if(id===selectedRef.current){const next=current[0]?.id||'';if(next)await select(next);else{selectedRef.current='';setSelectedState('');setMessages([])}}}),[operationCall,select])
  return {context,sessions,selected,messages,loading,error,operationError,operation,hasMore,currentDraft,setDraft,select,loadMore:()=>load(false),create,rename,remove,refreshMessages}
}
